name: build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - v*.*.*

jobs:
  create-build:
    uses: ./.github/workflows/shared-create-release.yml
    with:
      version_number: "${{github.ref_name}}.${{github.run_id}}"
      prerelease: true
