name: build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - v*.*.*

jobs:
  create-build:
    uses: ./.github/workflows/shared-create-release.yml
    with:
      version_number_suffix: ".${{github.run_number}}"
      prerelease: true

