name: build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - v*.*.*

jobs:
  get-version-number:
    runs-on: windows-latest
    outputs:
      versionNumber: ${{steps.readVersion.sthVersion}}
    steps:
      - uses: actions/checkout@v3
      - id: readVersion
        shell: pwsh
        run: |
          cd "${{github.workspace}}/src/SurviveTheHuntClient"
          $AssemblyInfo = cat .\Properties\AssemblyInfo.cs
          $AssemblyInfo -match '^\[assembly\: AssemblyVersion\(\"(?<version>\d+\.\d+\.\d+)\.\d+\"\)\]$'
          echo ("sthVersion=" + $Matches.version) >> "$GITHUB_OUTPUT"

  create-build:
    uses: ./.github/workflows/shared-create-release.yml
    needs: get-version-number
    with:
      version_number: "v${{needs.get-version-number.outputs.versionNumber}}.${{github.run_number}}"
      prerelease: true
