env:
  STH_CLIENT_SCRIPT: SurviveTheHuntClient.net.dll
  STH_SERVER_SCRIPT: SurviveTheHuntServer.net.dll
  STH_SHARED_LIB: SurviveTheHuntShared.net.dll
  NEWTONSOFT_JSON_DLL: Newtonsoft.Json.dll
  CONFIG_DIR: ${{github.workspace}}/configs/*

on:
  workflow_call:
    inputs:
      version_number:
        required: true
        type: string
      prerelease:
        required: false
        type: boolean
        default: true

jobs:
  release:
    permissions:
      contents: write
  
    env:
      sthArtifactName: sth-gamemode
    
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
      - uses: NuGet/setup-nuget@v1.2.0
      - 
        name: Run NuGet restore
        run: nuget restore sth-gamemode.sln
      - 
        name: Write new version number from tag
        run: |
            cd ./src
            echo "Writing new version number to client script"
            cd SurviveTheHuntClient 
            ../../scripts/update-assembly-version.ps1 ${{inputs.version_number}}
            echo "Writing new version number to server script"
            cd ../SurviveTheHuntServer
            ../../scripts/update-assembly-version.ps1 ${{inputs.version_number}}
            echo "Writing new version number to shared library"
            cd ../SurviveTheHuntShared
            ../../scripts/update-assembly-version.ps1 ${{inputs.version_number}}
        shell: pwsh
      - 
        name: Build
        # Supposedly OutputPath is meant to be relative to the PROJECT file, not cwd or even solution file. https://stackoverflow.com/a/4965607
        run: |
            mkdir artifacts
            mkdir artifacts/configs
            mkdir build
            msbuild.exe sth-gamemode.sln /p:platform="Any CPU" /p:configuration="Release" /p:OutputPath=..\..\build
      -
        name: Prepare artifacts
        shell: pwsh
        run: |
            copy fxmanifest.lua artifacts/fxmanifest.lua
            copy build/${{env.STH_CLIENT_SCRIPT}} artifacts/${{env.STH_CLIENT_SCRIPT}}
            copy build/${{env.STH_SERVER_SCRIPT}} artifacts/${{env.STH_SERVER_SCRIPT}}
            copy build/${{env.STH_SHARED_LIB}} artifacts/${{env.STH_SHARED_LIB}}
            copy build/${{env.NEWTONSOFT_JSON_DLL}} artifacts/${{env.NEWTONSOFT_JSON_DLL}}
            copy ${{env.CONFIG_DIR}} artifacts/configs/
            Compress-Archive -Path artifacts\* -DestinationPath ${{env.sthArtifactName}}-${{inputs.version_number}}.zip
      -
        if: ${{!inputs.prerelease}}
        name: Upload build to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{env.sthArtifactName}}-${{inputs.version_number}}.zip
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
      - 
        if: ${{inputs.prerelease == true}}
        name: Upload build to run artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.sthArtifactName}}-${{inputs.version_number}}
          path: artifacts/**/*
