env:
  STH_CLIENT_SCRIPT: SurviveTheHuntClient.net.dll
  STH_CLIENT_MODELS_SCRIPT: SurviveTheHuntClient.Models.net.dll
  STH_CLIENT_PLUGIN_GLOB: SurviveTheHuntClient.Plugins.*.net.dll
  STH_CLIENT_UI_SCRIPT: SurviveTheHuntClient.UI.net.dll
  LEMONUI_DLL: LemonUI.FiveM.dll
  STH_SERVER_SCRIPT: SurviveTheHuntServer.net.dll
  STH_SHARED_LIB: SurviveTheHuntShared.net.dll
  NEWTONSOFT_JSON_DLL: Newtonsoft.Json.dll
  CONFIG_DIR: ${{github.workspace}}/configs/*
  UI_FILE_DIR: ${{github.workspace}}/ui_files/*
  STH_EXTRAS_ROOT_DIR_NAME: "[sth-extras]"

on:
  workflow_call:
    inputs:
      version_number:
        required: true
        type: string
      prerelease:
        required: false
        type: boolean
        default: true
    secrets:
      sth_private_assets_pat:
        description: 'A token for pulling non-public asset repos'
        required: true

jobs:
  release:
    permissions:
      contents: write
  
    env:
      sthArtifactName: sth-gamemode
    
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
      - uses: NuGet/setup-nuget@v1.2.0
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/Krypton'
      - 
        name: Run NuGet restore
        run: nuget restore sth-gamemode.sln
      - 
        name: Write new version number from tag
        run: |
            cd ./src
            echo "Writing new version number to client script"
            cd SurviveTheHuntClient 
            ../../scripts/update-assembly-version.ps1 ${{inputs.version_number}}
            echo "Writing new version number to server script"
            cd ../SurviveTheHuntServer
            ../../scripts/update-assembly-version.ps1 ${{inputs.version_number}}
            echo "Writing new version number to shared library"
            cd ../SurviveTheHuntShared
            ../../scripts/update-assembly-version.ps1 ${{inputs.version_number}}
            cd ../SurviveTheHuntClient.UI
            ../../scripts/update-assembly-version.ps1 ${{inputs.version_number}}
        shell: pwsh
      - 
        name: Build
        # Supposedly OutputPath is meant to be relative to the PROJECT file, not cwd or even solution file. https://stackoverflow.com/a/4965607
        run: |
            mkdir artifacts
            mkdir artifacts/sth-gamemode
            mkdir artifacts/sth-gamemode/configs
            mkdir artifacts/sth-ui
            mkdir artifacts/sth-ui/files
            mkdir artifacts/${{env.STH_EXTRAS_ROOT_DIR_NAME}}
            mkdir build
            mkdir extra-src
            msbuild.exe sth-gamemode.sln /p:platform="Any CPU" /p:configuration="Release" /p:OutputPath=..\..\build
      - 
        name: Checkout extras (sth-cupid-av-controller)
        uses: actions/checkout@v6
        with:
          repository: 'tomezpl/sth-cupid-av-controller'
          token: ${{secrets.sth_private_assets_pat}}
          path: 'extra-src/sth-cupid-av-controller'
      - 
        name: Build extras (sth-cupid-av-controller)
        shell: pwsh
        run: |
          cd ${{github.workspace}}/extra-src/sth-cupid-av-controller
          npm install
          npm build
          mkdir ${{github.workspace}}/artifacts/${{env.STH_EXTRAS_ROOT_DIR_NAME}}/sth-cupid-av-controller
          cp fxmanifest.lua ${{github.workspace}}/artifacts/${{env.STH_EXTRAS_ROOT_DIR_NAME}}/sth-cupid-av-controller/fxmanifest.lua
          cp dist ${{github.workspace}}/artifacts/${{env.STH_EXTRAS_ROOT_DIR_NAME}}/sth-cupid-av-controller/dist
      -
        name: Prepare artifacts
        shell: pwsh
        run: |
            cd ${{github.workspace}}
            copy fxmanifest.lua artifacts/sth-gamemode/fxmanifest.lua
            copy uimanifest.lua artifacts/sth-ui/fxmanifest.lua
            copy build/${{env.STH_CLIENT_SCRIPT}} artifacts/sth-gamemode/${{env.STH_CLIENT_SCRIPT}}
            copy build/${{env.STH_CLIENT_MODELS_SCRIPT}} artifacts/sth-gamemode/${{env.STH_CLIENT_MODELS_SCRIPT}}
            Get-Item build/${{env.STH_CLIENT_PLUGIN_GLOB}} | ForEach-Object { Copy-Item -Path ($_.FullName) -Destination ([System.String]::Concat("artifacts/sth-gamemode/", $_.Name)) }
            copy build/${{env.STH_SERVER_SCRIPT}} artifacts/sth-gamemode/${{env.STH_SERVER_SCRIPT}}
            copy build/${{env.STH_SHARED_LIB}} artifacts/sth-gamemode/${{env.STH_SHARED_LIB}}
            copy build/${{env.STH_SHARED_LIB}} artifacts/sth-ui/${{env.STH_SHARED_LIB}}
            copy build/${{env.STH_CLIENT_UI_SCRIPT}} artifacts/sth-ui/${{env.STH_CLIENT_UI_SCRIPT}}
            copy build/${{env.STH_CLIENT_MODELS_SCRIPT}} artifacts/sth-ui/${{env.STH_CLIENT_MODELS_SCRIPT}}
            copy build/${{env.LEMONUI_DLL}} artifacts/sth-ui/${{env.LEMONUI_DLL}}
            copy build/${{env.NEWTONSOFT_JSON_DLL}} artifacts/sth-gamemode/${{env.NEWTONSOFT_JSON_DLL}}
            copy ${{env.CONFIG_DIR}} artifacts/sth-gamemode/configs/
            copy ${{env.UI_FILE_DIR}} artifacts/sth-ui/files/
            Compress-Archive -Path artifacts\* -DestinationPath ${{env.sthArtifactName}}-${{inputs.version_number}}.zip
      -
        if: ${{!inputs.prerelease}}
        name: Upload build to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{env.sthArtifactName}}-${{inputs.version_number}}.zip
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
      - 
        if: ${{inputs.prerelease == true}}
        name: Upload build to run artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.sthArtifactName}}-${{inputs.version_number}}
          path: artifacts/**/*
